name: lavue-blog
recipe: laravel
config:
  composer_version: '2.7.2'
  via: nginx
  webroot: public
  database: postgres
services:
  database:
    type: postgres:13
    portforward: true
    creds:
      database: blog_api
      username: postgres
      password: laravel
      port: 5432
